### ISSUE TITLE
Error in:ESP.Easy.Flasher Cannot show dialog

### ISSUE THREAD

**Issue by Domosapiens** [Grovkillen/ESP_Easy_Flasher#10]
@Grovkillen 
Just tried to execute the download 0.02
Run as administrator on WIN7
I see expanding to a number of sub-directories.
But with this error:
![error capture](https://user-images.githubusercontent.com/35063211/47776292-5ae5b500-dcf2-11e8-90b4-da2e830575fc.JPG)

Important?

I saw later that ESP.Easy.Flasher is now included in the ESP distribution.
If I execute it there, within the folder, then .... no error message !!

**Comment by Grovkillen** [comment]
I know... I made a "small" error when updating the file. I will have it sorted this evening. You can hit abort and then restart and it'll not show up any more. I'm calling for a resource not there yet. If you use the file that is part of the nightly release in ESP Easy (today is the first one delivered with the flasher) I fixed it in that one but didn't have the time to update the repository.

**Comment by Domosapiens** [comment]
Great. Thanks
