### ISSUE TITLE
Support for High DPI?

### ISSUE THREAD

**Issue by olskar** [Grovkillen/ESP_Easy_Flasher#12]
I am running this on a high dpi screen, I guess that is the reason my application window looks like this?

Would be nice if high dpi support could be implemented
![dpi](https://user-images.githubusercontent.com/18314560/47998958-3b3efa00-e101-11e8-8072-a46f850a4d53.png)

**Comment by Grovkillen** [comment]
You can fix it by saving the settings (to a file) and in the settings folder you find the ini file. In the bottom of it you just change the PIXELS PER INCH to something else. Save and restart the app.
