### ISSUE TITLE
Given Name and Number are not used

### ISSUE THREAD

**Issue by Domosapiens** [Grovkillen/ESP_Easy_Flasher#13]
Given Unit Name and Number are not used in Flash tool. (0.02.000)
Saw a name .. something with ESP_xxx, and no number
(used without Admin PW setting)
Other params. works fine!

**Comment by Grovkillen** [comment]
I think it's a temporary problem for some units? Sometimes the programer doesn't get a response from the unit until a third or fourth try.

**Comment by Domosapiens** [comment]
Corrected later by hand.
No big deal.
Will try again with a next batch.
