### ISSUE TITLE
Display scaling

### ISSUE THREAD

**Issue by Phrede** [Grovkillen/ESP_Easy_Flasher#15]
My display is set to 1920 X 1080 on my workbench machine.  If anything other than 100% the program window is clipped of and unusable.

**Comment by Grovkillen** [comment]
You can test to save the settings and then open the settings.ini file. Pixels per inch. Test some other value and save+restart.

**Comment by Grovkillen** [comment]
Can we close this one or is is still an issue? If yes, the comment here and I'll reopen it.
