### ISSUE TITLE
Json Error

### ISSUE THREAD

**Issue by adrya87** [Grovkillen/ESP_Easy_Flasher#17]
I'm Have this Problem.
At the startup display this error:

Error in ESP.Easy.Flasher.EXE
Line:71 - (1:1) Unquoted string in JSON data only valid for dictionary names.

Thanks

**Comment by Grovkillen** [comment]
What version?

**Comment by adrya87** [comment]
sorry 4.001 on windows 10 pro 64-bit

**Comment by Grovkillen** [comment]
Please update to 0.04.002

Den ons 16 jan. 2019 17:16 skrev adrya87 <notifications@github.com>:

**Comment by Grovkillen** [comment]
This should be fixed now.
