### ISSUE TITLE
2 possible ideas

### ISSUE THREAD

**Issue by giig1967g** [Grovkillen/ESP_Easy_Flasher#2]
Hi,
just sending a couple of ideas:
 
1) would it be possible to load a config file during the flash process?
2) would it be possible to change the IP and wifi settings of an already flashed unit?
(in other words, assume you have a ESP unit misconfigured and want to change just the IP or wifi SSID)

thanks

**Comment by Grovkillen** [comment]
I'm planning on letting netscan do those things.

**Comment by Grovkillen** [comment]
And a yet to be developed app to talk serial.

**Comment by giig1967g** [comment]
nice ideas

**Comment by Grovkillen** [comment]
You can now do serial programing only as of 0.00.026
