### ISSUE TITLE
Alpha  ?

### ISSUE THREAD

**Issue by Oxyandy** [Grovkillen/ESP_Easy_Flasher#3]
Win10 x64, Regional Settings English AU, 
display resolution 1920 x 1080

 ![Alpha ???](https://user-images.githubusercontent.com/36609061/37381950-2a283e4c-2794-11e8-9a56-e7434aaa3ab6.jpg)

**Comment by Grovkillen** [comment]
I know, it's the Win10 scaling that does that... sorry but I don't have a solution for it yet.

**Comment by Oxyandy** [comment]
Any chance you could post a screen shot then so I can see all the text & then make use of your program, it look like a time saver, cheers
EDIT: what it should look like found here
https://github.com/Grovkillen/ESP_Easy_Flasher/blob/master/README.md

**Comment by Grovkillen** [comment]
If you install the font, it'll look better

**Comment by Oxyandy** [comment]
Sure, the font name will help 
thanks

**Comment by Grovkillen** [comment]
It should be included with the exe? If it won't work it's the Agency FB
font.

Den lör 17 mars 2018 17:59Oxyandy <notifications@github.com> skrev:

**Comment by Oxyandy** [comment]
Ok yes thanks, that worked - it is still slightly too tall for the screen, but everything is now visible - Thanks
