### ISSUE TITLE
COM port is already in use. Cannot proceed.

### ISSUE THREAD

**Issue by Domosapiens** [Grovkillen/ESP_Easy_Flasher#8]
On WIN7 this is the log:

> DONE!
> (You may disconnect the unit if you want.)
> **COM port is already in use. Cannot proceed.**
> Adding settings using SERIAL commands.
> Flashing done (76.4s).
> Start flashing on COM18 (This might take a minute or two...)
> 
Any idea how to deal with this?

**Comment by Grovkillen** [comment]
Sometimes you may need to do a manual reboot after the flash. Have you tried that?

**Comment by Domosapiens** [comment]
Will try at the next occasion. Thanks

**Comment by Domosapiens** [comment]
@Grovkillen 
Manual reboot does not solve it -- COM port is already in use. Cannot proceed
Re-connect does not solve it -- COM port is already in use. Cannot proceed
Re-connect and then: Program only -- COM port is already in use. Cannot proceed
Re-connect and then: Open serial monitor -- COM port is already in use. Cannot proceed
Please advice (for WIN7)
5 units are hungry for the latest release

**Comment by Grovkillen** [comment]
That is really weird! I can only reproduce this if I have the serial monitor active or if the app has crashed before and is still keeping the port open... have you looked through the processes?

**Comment by Grovkillen** [comment]
Is this still an issue?

**Comment by Domosapiens** [comment]
@Grovkillen There is 1 ESP.Easy.Flasher.exe process running
Are there other processes I have to look for?

Flashing goes well, but post flash action fails.
So there is initial a correct connection between the app and the ESP for flash.

If I restart the app and go directly to Program only: the COM port is already in use.

Disconnect, connect the USB, removes and creates USB-Serial CH340 (COM21).
That one is recognized in the app.
When I push "Program only" I see shortly a new process dllhost.exe *32 COM surrogate
in addition to the dllhost.exe COM surrogate (without *32)  that is running all the time, with and without the USB plugged.

Does one of above ring any bell for you?

**Comment by Grovkillen** [comment]
I will look into that. Could be some dependences not working correctly in
your environment.

Den tors 1 nov. 2018 23:04 skrev Domosapiens <notifications@github.com>:

**Comment by Grovkillen** [comment]
Please update to 0.04.003 and report back here if this still is an issue.

**Comment by bennybubble** [comment]
Using 0.04.007 and still an issue, using WIN10.
Tried running as administrator also no difference, flashing goes well!

**Comment by marsic-84** [comment]
same problem(((

**Comment by sascha777** [comment]
Just ran into the same problem.
Got it working since I opened up the Serial Monitor. After that it doesn't work anymore.
Tried reboot without success.
Any updates on this?

**Comment by BagheeraHans** [comment]
Same issue here, used several board and flash tools.
On two different computers

**Comment by zwinsch** [comment]
Same issue - with Win7 and (0.04.007)

**Comment by Fgagnebien** [comment]
Ran into the same problem.
Using 0.04.007 and  WIN10.
Tried running as administrator also no difference, flashing goes well!
Still same issue,
COM port is already in use. Cannot proceed.

**Comment by bbfendt** [comment]
Hello and thx for your great Software !
Same Problem for me here: "COM port is already in use. Cannot proceed"
Occurs after flashing with "post flash action" checked but also when just using "program only" or even when trying to open the Serial Monitor.
Only one instance running.
OS: Win10 x64
Version of Software: 0.04.007 and older versions too

**Comment by nygellyndley** [comment]
I seem to be having the same issue.
Even just a straight "program" after a flash and esp reboot "COM port is already in use.  Cannot proceed."
Tried as admin

**Comment by Grovkillen** [comment]
Yep I totally get the bug here, and I'm currently working on a better flasher tool which doesn't require you to download an exe and it will work on most types of host systems (may it be PC, tablet, phone or Chromebook).



// Jimmy Westberg
0706505709
٩(- ̮̮̃-̃)۶

Den 2020-12-29 20:26:48 skrev Nygel Lyndley <notifications@github.com>:
I seem to be having the same issue.
Even just a straight "program" after a flash and esp reboot "COM port is already in use. Cannot proceed."
Tried as admin

**Comment by Fr-Mike38** [comment]
Not a recent thread, but as it helped me today, I just share that all issues encountered when uploading firm on Sonoff where solved by :
- using a powered hub and short connections between USB-to-serial key and Sonoff PCB
- lauching ESP.Easy.Flasher.exe  in admin mode (W7+ESP flasher 0.04.007)

With these two 'rules', upload runs correctly from begin to end.

If this can help somebody !
